import { expect, test } from "@playwright/test"

test("compares a preset with local tokenizers", async ({ page }) => {
  await page.goto("/")
  await expect(page.getByRole("heading", { level: 1, name: "Connor’s Tokenizer" })).toBeVisible()
  await expect(page.getByRole("tab", { name: "Compare text" })).toHaveAttribute("aria-selected", "true")
  const openAi = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "OpenAI" }) })
  await expect(openAi.locator(".lab-mark")).toHaveText("OA")
  await expect(openAi.getByText("ready · local")).toBeVisible({ timeout: 30_000 })
  await expect(openAi.locator(".metric-primary > span")).toHaveText("tokens")
  await expect(openAi.locator(".metric-primary strong")).toHaveText(/^\d+$/)
  const connorsTokenizer = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Connor’s Tokenizer" }) })
  await expect(connorsTokenizer.locator(".metric-primary strong")).toHaveText(/^\d+$/, { timeout: 30_000 })
  await expect(openAi.getByRole("button", { name: "Text" })).toHaveAttribute("aria-pressed", "true")
  await openAi.getByRole("button", { name: "Token IDs" }).click()
  await expect(openAi.getByRole("button", { name: "Token IDs" })).toHaveAttribute("aria-pressed", "true")
  await expect(openAi.locator(".token-segment.is-id").first()).toBeVisible()

  await page.getByRole("button", { name: "Multilingual" }).click()
  await expect(page.getByLabel("Text to compare")).toHaveValue(/你好世界/u)
  await expect(page.getByText("ready · local", { exact: true })).toHaveCount(8, { timeout: 30_000 })
  await expect(page.getByText("ready · local proxy", { exact: true })).toHaveCount(2, { timeout: 30_000 })
  await expect(page.getByText("10 / 10 measured")).toBeVisible()
  await expect(page.getByRole("heading", { name: "Results" })).toBeVisible()
  const promptRuler = page.getByRole("list", { name: "Token counts ranked from smallest to largest" })
  await expect(promptRuler.locator(".ruler-score").first()).toHaveAttribute("data-best", "true")
  await expect(promptRuler.locator(".ruler-score[data-best='true']")).toHaveCount(1)
  const anthropic = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Anthropic" }) })
  const xai = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "xAI" }) })
  await expect(anthropic.getByRole("button", { name: "Token IDs" })).toBeVisible()
  await expect(xai.getByRole("button", { name: "Token IDs" })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

test("runs the fixed benchmark suite in a separate view", async ({ page }) => {
  await page.goto("/")
  await expect(page.getByText("10 / 10 measured")).toBeVisible({ timeout: 30_000 })
  const benchmarkTab = page.getByRole("tab", { name: "Benchmark suite" })
  await benchmarkTab.click()
  await expect(benchmarkTab).toHaveAttribute("aria-selected", "true")
  await expect(page.getByRole("heading", { name: "Benchmark corpus" })).toBeVisible()
  await expect(page.locator(".suite-facts").getByText("2,116", { exact: true })).toBeVisible()
  await expect(page.getByLabel("Text to compare")).not.toBeVisible()

  const benchmarkTable = page.getByRole("table", { name: /UTF-8 bytes per token for every benchmark track/ })
  await expect(benchmarkTable).toBeVisible()
  await expect(benchmarkTable.locator("tbody tr")).toHaveCount(19)
  await expect(benchmarkTable.getByRole("columnheader", { name: /Connor’s Tokenizer/i })).toBeVisible()
  await expect(benchmarkTable.getByRole("row", { name: /^Wikipedia / })).not.toContainText("—")
  await expect(benchmarkTable.getByRole("row", { name: /^Python / })).toBeVisible()
  await expect(benchmarkTable.getByRole("row", { name: /^TokenizerBench · 84 languages / })).toBeVisible()
  await expect(benchmarkTable.getByRole("row", { name: /^Wikipedia / }).locator("td[data-best='true'] .benchmark-best")).toBeVisible()
  const toklensTable = page.getByRole("table", { name: /TokLens-compatible intrinsic metrics/ })
  await expect(toklensTable.getByRole("row", { name: /Google/ }).locator("td[data-best='true']").first().locator(".benchmark-best")).toBeVisible()
  await expect(toklensTable.getByRole("row", { name: /Connor’s Tokenizer/ }).locator("td").first().locator(".benchmark-best")).toHaveCount(0)
  const benchmarkData = page.locator("details.benchmark-data").first()
  await expect(benchmarkData).toHaveAttribute("open", "")
  const sourceTitle = benchmarkData.getByRole("link", { name: "Pride and Prejudice" })
  await expect(sourceTitle).toBeVisible()
  const sourceTitleBox = await sourceTitle.boundingBox()
  const sourceMetadataBox = await sourceTitle.locator("xpath=..").locator("span").boundingBox()
  expect(sourceTitleBox?.width).toBeGreaterThan(120)
  expect(sourceMetadataBox?.y).toBeGreaterThan(sourceTitleBox?.y ?? 0)
  await expect(
    benchmarkData.getByRole("link", { name: "What does the yield keyword do in Python?", exact: true }),
  ).toBeVisible()
  await expect(page.getByRole("heading", { name: "TokenizerBench 0.2.0" })).toBeVisible()
  await expect(page.getByRole("heading", { name: "TokLens · ACL 2026" })).toBeVisible()
  await expect(page.getByRole("heading", { name: "TokenMonster · 16 models" })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)

  await page.getByRole("tab", { name: "Compare text" }).click()
  await expect(page.getByLabel("Text to compare")).toHaveValue(/A tokenizer splits text/u)
})

test("does not expose hosted-provider transmission", async ({ page }) => {
  await page.goto("/")
  await expect(page.getByText("10 / 10 measured")).toBeVisible({ timeout: 30_000 })
  await expect(page.getByText("Hosted providers")).toHaveCount(0)
  await expect(page.getByRole("button", { name: /hosted providers/i })).toHaveCount(0)
  expect(await page.evaluate(() => localStorage.getItem("connors-tokenizer:hosted-consent"))).toBeNull()
})
